# Site settings
title: Nikita Kazeichev | Блог о web-разработке
description: Блог о web-разработке
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nikita Kazeichev
user_title: Блог о web-разработке
email: kazeichev@yandex.ru
github_username:  kazeichev

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
timezone: Europe/Moscow

# Post settings
future: true

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Статьи
    url: /
  - title: Об авторе
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
